# download base image
# python 2
# FROM continuumio/anaconda
# python 3
FROM continuumio/anaconda3

# set working directory
WORKDIR /usr/src/app

COPY ./src/e-mission-server/ ./

# Upgrade pip
RUN pip install --upgrade pip

# setup python environment
RUN conda env update --name emission --file setup/environment36.yml
RUN /bin/bash -c "source activate emission; pip install six --upgrade"

# Add dependencies (for importing test data)
# i.e. test_july_22
RUN pip install future pymongo arrow attrdict geojson utm pygeocoder jsonpickle

# install nodejs, npm and bower
RUN apt-get update
RUN apt-get install -y build-essential cron
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get -y install nodejs
RUN npm install -g bower
WORKDIR /usr/src/app/webapp
RUN bower update --allow-root
WORKDIR /usr/src/app

# install nano for debugging
RUN apt-get -y install nano

# Add analysis pipeline cronjob
ADD ./res/e-mission-server/scripts/run.cronjob.sh /usr/src/app/run.cronjob.sh
RUN chmod u+x /usr/src/app/run.cronjob.sh
ADD ./res/e-mission-server/scripts/crontab /etc/cron.d/pipeline-cron
RUN chmod 0644 /etc/cron.d/pipeline-cron
RUN mkdir /var/log/emission

# start the server and run cron
ADD ./res/e-mission-server/scripts/run.app.sh /usr/src/app/run.app.sh
RUN chmod u+x /usr/src/app/run.app.sh

EXPOSE 8080

CMD ["/bin/bash", "/usr/src/app/run.app.sh"]
